name: loveforever
favicon: null
layout_spectrum: 0.9983888
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "LOVE - more than a rock n' roll band - a movement!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f80000'
    - '#010000'
    - '#6d0000'
    - '#f45810'
    - '#fccb31'
  brandStrength: 0.9575725
  lightness: 0.5552714448422194
  saturation: 0.631121237995103
  rhythmicContrast: 0.2242724162060767
purpose: []
